image: python:3.8-buster

before_script:
  - pip install -r .mkdocs/requirements.txt

test:
  stage: test
  script:
  - mkdir docs
  - cp *md ./docs
  - mkdocs build --strict --verbose --site-dir test -f .mkdocs/mkdocs.yml
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - mkdir docs
  - cp *md ./docs
  - mkdocs build --strict --verbose -f .mkdocs/mkdocs.yml
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

