image: python:3.8-buster

before_script:
  - pip install -r requirements.txt
  - pip install git+https://${GH_API_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

pages:
  stage: deploy
  script:
  - mkdocs build -f mkdocs.yml
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
