site_name: JATIC Onboading documentation
repo_name: Gitlab
site_url: https://jatic.pages.jatic.net/cdao/docs
repo_url: https://gitlab.jatic.net/cdao/docs
site_dir: public
docs_dir: docs
theme: material

nav:
  - Home: 'index.md'
  - 'Program background':
    - 'Program Origin': 'program-background/origin.md'
    - 'Capability Description': 'program-background/cap-description.md'
    - 'FAQs': 'empty.md'
    - 'Supported Personas': 'program-background/roles.md'
    - 'Supported Use Cases': 'program-background/datasets.md'
  - 'Projects':
    - 'MAITE': 'empty.md'
    - 'RAVEN': 'empty.md'
    - 'XAITK': 'empty.md' 
    - 'NRTK': 'empty.md'
    - 'DAML': 'empty.md'
    - 'heART': 'empty.md'
    - 'Armory': 'empty.md'
    - 'Gradient': 'empty.md'
    - 'RealLabel': 'empty.md'
    - 'Survivor': 'empty.md'
  - 'Program Organization':
    - 'Software Development Methodology': 'org-process/agile-methodology.md'
    - 'Agile Roles': 'org-process/agile-roles.md'
    - 'Shared principles': 'org-process/shared-principles.md'
    - 'Increment planning': 'empty.md'
  - 'Platforms Usage Guide':
    - 'Platforms overview': 'empty.md'
    - 'Gitlab introduction': 'empty.md'
    - 'Slack introduction': 'platforms/slack-usage.md'
    - 'Mural introduction'
    - 'Using Gitlab for Agile': 'platforms/gitlab-agile.md'
    - 'Navigating Gitlab': 'platforms/gitlab-org.md'
  - 'Software Development Plan':
    - 'Common Protocols': 'sdp/protocols.md'
    - 'Testing Requirements': 'sdp/testing-plan.md'
    - 'DevSecOps Requirements': 'sdp/devsecops.md'
    - 'Software Requirements': 'sdp/software-requirements.md'
    - 'Branch, Merge, Release Guidance': 'sdp/branch-merge-release.md'
    - 'Open-sourcing Guidance': 'sdp/open-source-strategy.md'
    - 'General Python Coding Guidelines': 'sdp/coding-guidelines.md'
  - 'Reference Material':
    - 'Program Org Chart': 'reference/org-chart.md'