site_name: JATIC Onboading documentation
repo_name: Gitlab
site_url: https://jatic.pages.jatic.net/cdao/docs
repo_url: https://gitlab.jatic.net/cdao/docs
site_dir: public
docs_dir: docs
theme: material

nav:
  - Home: 'index.md'
  - 'Program background':
    - 'Program Origin': 'program-background/origin.md'
    - 'Capability Description': 'program-background/cap-description.md'
    - 'FAQs': 'empty.md'
    - 'Supported Personas': 'program-background/roles.md'
    - 'Supported Use Cases': 'program-background/datasets.md'
  - 'Products': 'products.md'
  - 'Software Development Process':
    - 'Agile Framework & Principles': 'org-process/safe.md'
    - 'Team Roles & Responsibilities': 'org-process/roles.md'
    - 'Program-level Events': 'org-process/program-events.md'
    - 'Team-level Events': 'org-process/team-events.md'
  - 'Platforms Usage Guide':
    - 'Platforms overview': 'empty.md'
    - 'Gitlab introduction': 'empty.md'
    - 'Slack introduction': 'platforms/slack-usage.md'
    - 'Mural introduction': 'empty.md'
    - 'Using Gitlab for Agile': 'platforms/gitlab-agile.md'
    - 'Navigating Gitlab': 'platforms/gitlab-org.md'
  - 'Software Requirements':
    - 'Common Protocols': 'sdp/protocols.md'
    - 'Testing Requirements': 'sdp/testing-plan.md'
    - 'DevSecOps Requirements': 'sdp/devsecops.md'
    - 'Software Requirements': 'sdp/software-requirements.md'
    - 'Branch, Merge, Release Guidance': 'sdp/branch-merge-release.md'
    - 'Open-sourcing Guidance': 'sdp/open-source-strategy.md'
    - 'General Python Coding Guidelines': 'sdp/coding-guidelines.md'
  - 'Reference Material':
    - 'Program Org Chart': 'reference/org-chart.md'
    - 'Program Calendar': 'reference/sprint-calendar.md'
    