site_name: JATIC Onboading documentation
repo_name: Gitlab
site_url: https://jatic.pages.jatic.net/cdao/docs
repo_url: https://gitlab.jatic.net/cdao/docs
site_dir: public
docs_dir: docs
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.footer
    - navigation.instant
    - navigation.top
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: green
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
      primary: indigo
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.jatic.net/
    - icon: fontawesome/brands/slack
      link: https://cdaote.slack.com/
    - icon: fontawesome/solid/envelope
      link: mailto:<cdao-jatic@mail.mil>
  generator: false

nav:
  - 'Home': 
    - index.md
    - 'Program background':
      - program-background/index.md
      - 'Capability Description': 'program-background/cap-description.md'
      - 'FAQs': 'empty.md'
      - 'Supported Use Cases & Roles': 'program-background/use-cases-roles.md'
    - 'Products':
      - 'Armory': 'products/armory.md'
      - 'Adversarial Robustness Toolbox': 'products/art.md'
      - 'DAML': 'products/daml.md'
      - 'Gradient': 'products/gradient.md'
      - 'MAITE': 'products/maite.md'
      - 'NRTK': 'products/nrtk.md'
      - 'RAVEN': 'products/raven.md'
      - 'XAITK': 'products/xaitk.md'
  - 'Software Development Process':
    - dev-process/index.md
    - 'Key Agile Principles': 'dev-process/agile-principles.md'
    - 'Team Roles & Responsibilities': 'dev-process/roles.md'
    - 'Program-level Events': 'dev-process/program-events.md'
    - 'Team-level Events': 'dev-process/team-events.md'
    - 'Common Platforms': 'dev-process/common-platforms.md'
  - 'Platforms Usage Guide':
    - platforms/index.md
    - 'Onboarding Guide': 'platforms/onboarding.md'
    - 'Slack Usage Guide': 'platforms/slack.md'
    - 'Gitlab Usage Guide': 'platforms/gitlab.md'
    - 'Using Gitlab for Agile': 'platforms/gitlab-agile.md'
    - 'Navigating Gitlab': 'platforms/gitlab-org.md'
  - 'Software Requirements':
    - 'Common Protocols': 'sdp/protocols.md'
    - 'Testing Requirements': 'sdp/testing-plan.md'
    - 'DevSecOps Requirements': 'sdp/devsecops.md'
    - 'Software Requirements': 'sdp/software-requirements.md'
    - 'Branch, Merge, Release Guidance': 'sdp/branch-merge-release.md'
    - 'Open-sourcing Guidance': 'sdp/open-source-strategy.md'
    - 'General Python Coding Guidelines': 'sdp/coding-guidelines.md'
  - 'Program Organization':
    - 'Calendar': 
      - 'Increment 4 (31 JAN 24 - 23 APR 24)': 'calendar/inc4.md'
      - 'Increment 3 (11 OCT 23 - 30 JAN 24)': 'calendar/inc3.md'
    - 'Org Chart':
      - 'ARiA': 'org-chart/aria.md'
      - 'IBM': 'org-chart/ibm.md'
      - 'Kitware': 'org-chart/kitware.md'
      - 'MIT-LL': 'org-chart/mitll.md'
      - 'MORSE': 'org-chart/morse.md'
      - 'Team MetroStar': 'org-chart/metrostar.md'
      - 'PM Team': 'org-chart/pm.md'
      - 'System Team': 'org-chart/systems.md'
      - 'TwoSix': 'org-chart/twosix.md'
    