site_name: JATIC Internal Docs
repo_name: Gitlab
site_url: https://jatic.pages.jatic.net/docs
repo_url: https://gitlab.jatic.net/docs
site_dir: public
docs_dir: docs
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.footer
    - navigation.instant
    - navigation.top
    - navigation.expand
  logo: assets/logo.jpg # upgrade to SVG later
  favicon: assets/logo.jpg # upgrade to SVG later
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
      primary: indigo
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: green
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.jatic.net/
    - icon: fontawesome/brands/slack
      link: https://cdaote.slack.com/
    - icon: fontawesome/solid/envelope
      link: mailto:<cdao-jatic@mail.mil>
  generator: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - 'Home': 
    - index.md
    - 'Program Info':
      - program-info/index.md
      - 'Capability Description': 'program-info/cap-description.md'
      - 'Documented Need': 'program-info/documented-need.md'
      - 'Supported Use Cases': 'program-info/use-cases.md'
      - 'Supported Roles & Personas': 'program-info/roles-personas.md'
      - 'FAQs': 'program-info/faq.md'
    - 'Products':
      - products/index.md
      - 'Armory': 'products/armory.md'
      - 'Adversarial Robustness Toolbox': 'products/art.md'
      - 'DAML': 'products/daml.md'
      - 'Gradient': 'products/gradient.md'
      - 'MAITE': 'products/maite.md'
      - 'NRTK': 'products/nrtk.md'
      - 'RAVEN': 'products/raven.md'
      - 'XAITK': 'products/xaitk.md'
  - 'Processes': # this name seems reasonable
    - 'Software Development Process': # this name seemed most emcompassing of the actual content. of course, it clashes with the SDP. but maybe SDP should be renamed? seems more like requirements.
      - dev-process/index.md
      - 'Key Agile Principles': 'dev-process/agile-principles.md'
      - 'Team Roles & Responsibilities': 'dev-process/roles.md'
      - 'Program-level Events': 'dev-process/program-events.md'
      - 'Team-level Events': 'dev-process/team-events.md'
    - 'Shared Platforms':
      - platforms/index.md
      - 'Slack Usage': 'platforms/slack.md'
      - 'Gitlab Usage': 'platforms/gitlab.md'
      - 'Gitlab for Agile Software Development': 'platforms/gitlab-agile.md'
  - 'Requirements & Guidelines': # this name seems reasonable
      - 'Software':
        - sdp/index.md
        - 'Common Protocols': 'sdp/protocols.md'
        - 'Testing Requirements': 'sdp/testing-plan.md'
        - 'DevSecOps Requirements': 'sdp/devsecops.md'
        - 'Software Requirements': 'sdp/software-requirements.md'
        - 'Branch, Merge, Release Guidance': 'sdp/branch-merge-release.md'
        - 'General Python Coding Guidelines': 'sdp/coding-guidelines.md'
      - 'Product':
        - guidelines/index.md
        - 'Open-sourcing Guidelines': 'guidelines/open-source.md'
        - 'Product Naming Guidelines': 'guidelines/naming.md'
  - 'Calendar': 
    - 'Increment Calendar':
      - 'Increment 3 (11 OCT 23 - 30 JAN 24)': 'calendar/inc3.md'
      - 'Increment 4 (31 JAN 24 - 23 APR 24)': 'calendar/inc4.md'
      - 'Increment 5 (24 APR 24 - 15 JUL 24)': 'calendar/inc5.md'
    - 'Calendar repo': 
      - 'link': https://gitlab.jatic.net/jatic/calendar
  - 'Teams':
    - 'ARiA': 'teams/aria.md'
    - 'IBM': 'teams/ibm.md'
    - 'Kitware': 'teams/kitware.md'
    - 'MIT-LL': 'teams/mitll.md'
    - 'MORSE': 'teams/morse.md'
    - 'Team MetroStar': 'teams/msqs.md'
    - 'PM Team': 'teams/pm.md'
    - 'System Team': 'teams/systems.md'
    - 'TwoSix': 'teams/twosix.md'
  - 'Presentations': # use to host all of our demo videos and presentations. need to figure out how to do this.
    - presentations/index.md
  - 'Program Board': https://app.mural.co/t/ecis6578/m/ecis6578/1697134244478/58b5177575b43e6f5caf6feb82d840410a6ceff5?sender=u4d7fc200d51cbdba67ba7346
