# Project information
site_name: JATIC Internal Docs
site_author: CDAO Assessment & Assurance
site_description: >-
  Enabling DoD AI test & evaluation

# Repo information
repo_url: https://gitlab.jatic.net/jatic/internal-docs

# Build information
site_dir: public
docs_dir: docs

# Theme configuration
theme:
  name: material
  features:
    - navigation.instant # disable when generating documentation for offline use
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.path # this currently only works on the Material for MkDocs insider's edition
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - search.share
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
      primary: indigo
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: green
  logo: assets/logo-white.png
  favicon: assets/logo-blue.png

# MkDocs plugins
plugins:
  # - offline # enable when trying to generate offline documentation (i.e., can be sent in a .zip)
  - search
  - tags:
      tags_file: tags.md

# Additional configurations
extra_css:
  - stylesheets/extra.css
extra: # These generate the footer
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:<CDAO-jatic@groups.mail.mil> 
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.jatic.net/
    - icon: fontawesome/brands/slack
      link: https://cdaote.slack.com/
    - icon: simple/mural # the mural link below needs to be updated with the latest program board each increment!
      link: https://app.mural.co/t/ecis6578/m/ecis6578/1697134244478/58b5177575b43e6f5caf6feb82d840410a6ceff5?sender=u4d7fc200d51cbdba67ba7346 
  generator: false

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 3

# Page tree
nav: 
  - Home: 
    - index.md
    - Program Info:
      - info/index.md # potentially redo this page to be an overview page with grid cards
      - Problem Statement: info/problem-statement.md
      - Capability Overview: info/capability-overview.md
      - Design Principles: info/design-principles.md
      - Supported Applications: info/supported-applications.md
      - Supported Roles & Personas: info/supported-roles-personas.md
      - FAQ: info/faq.md
    - About this site : about.md
  - Products:
    - products/index.md
    # consider removing these
    - Armory: products/armory.md
    - Adversarial Robustness Toolbox: products/art.md
    - DAML: products/daml.md
    - Gradient: products/gradient.md
    - MAITE: products/maite.md
    - NRTK: products/nrtk.md
    - RAVEN: products/raven.md
    - XAITK: products/xaitk.md
  - Shared Processes: 
    - process/index.md
    - Agile Methodology:
      - process/agile/index.md
      - Key Principles: process/agile/principles.md
      - Team Roles & Responsibilities: process/agile/roles.md
      - Program-level Events: process/agile/program-events.md
      - Team-level Events: process/agile/team-events.md
    - Common Platforms:
      - process/platforms/index.md
      - Slack Usage: process/platforms/slack.md
      - Gitlab Usage: process/platforms/gitlab.md
    - Guides:
      - Gitlab for Agile Software Development: process/guides/gitlab-agile.md
      - User Engagement Guide: process/guides/user-engagement.md
  - Policies & Guidelines: 
      - policy/index.md
      - For Software: # each of these should be brought under the "policy" folder eventually
        - sdp/index.md
        - Common Protocols: sdp/protocols.md
        - Testing Requirements: sdp/testing-plan.md
        - DevSecOps Requirements: sdp/devsecops.md
        - Software Requirements: sdp/software-requirements.md
        - Branch, Merge, Release Guidance: sdp/branch-merge-release.md
        - General Python Coding Guidelines: sdp/coding-guidelines.md
      - For Documentation:
        - policy/documentation/index.md
      - For Products:
        - policy/product/index.md
        - Classification Policy: policy/product/classification.md
        - Data Rights & Licensing Policy: policy/product/data-rights-licensing.md
        - Product Naming Guidelines: policy/product/naming.md
        - Public Release Guidelines: policy/product/public-release.md
  - Increment Info:
    - increment/index.md
    - Calendar: increment/calendar.md
  #- Presentations: 
  #  - presentations/index.md 
  - Teams:
    - teams/index.md
    - ARiA: teams/aria.md
    - IBM: teams/ibm.md
    - Kitware: teams/kitware.md
    - MIT-LL: teams/mitll.md
    - MORSE: teams/morse.md
    - PM Team: teams/pm.md
    - System Team: teams/systems.md
    - Team MetroStar: teams/msqs.md
    - TwoSix: teams/twosix.md
