site_name: JATIC Internal Docs
repo_name: Gitlab
site_url: https://jatic.pages.jatic.net/docs
repo_url: https://gitlab.jatic.net/docs
site_dir: public
docs_dir: docs
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.footer
    - navigation.instant
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.path # this will only work on the Material for MkDocs insider's edition
  logo: assets/logo-white.png
  favicon: assets/logo-blue.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
      primary: indigo
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: green
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.jatic.net/
    - icon: fontawesome/brands/slack
      link: https://cdaote.slack.com/
    - icon: fontawesome/solid/envelope
      link: mailto:<cdao-jatic@mail.mil> # check that this is correct
  generator: false
# plugins:
#  - git-revision-date-localized:
#      enable_creation_date: true
#      type: timeago
#  - git-authors
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - 'Home': 
    - index.md
    - 'Program Info':
      - program-info/index.md
      - 'Problem Statement': 'program-info/problem-statement.md'
      - 'Design Principles': 'program-info/design-principles.md'
      - 'Supported Applications': 'program-info/supported-applications.md'
      - 'Supported Roles & Personas': 'program-info/supported-roles-personas.md'
      - 'FAQ': 'program-info/faq.md'
    - 'Products':
      - products/index.md
      - 'Armory': 'products/armory.md'
      - 'Adversarial Robustness Toolbox': 'products/art.md'
      - 'DAML': 'products/daml.md'
      - 'Gradient': 'products/gradient.md'
      - 'MAITE': 'products/maite.md'
      - 'NRTK': 'products/nrtk.md'
      - 'RAVEN': 'products/raven.md'
      - 'XAITK': 'products/xaitk.md'
    - 'About this site' : 'about.md'
  - 'Processes': # this name seems reasonable
    - 'Software Development Process': # this name seemed most emcompassing of the actual content. of course, it clashes with the SDP. but maybe SDP should be renamed? seems more like requirements.
      - process/dev/index.md
      - 'Key Agile Principles': 'process/dev/agile-principles.md'
      - 'Team Roles & Responsibilities': 'process/dev/roles.md'
      - 'Program-level Events': 'process/dev/program-events.md'
      - 'Team-level Events': 'process/dev/team-events.md'
    - 'Shared Platforms':
      - process/platforms/index.md
      - 'Slack Usage': 'process/platforms/slack.md'
      - 'Gitlab Usage': 'process/platforms/gitlab.md'
    - 'Guides':
      - 'Gitlab for Agile Software Development': 'process/guides/gitlab-agile.md'
      - 'User Engagement Guide': 'process/guides/user-engagement.md'
  - 'Requirements & Guidelines': # this name seems reasonable
      - requirements/index.md
      - 'Software':
        - sdp/index.md
        - 'Common Protocols': 'sdp/protocols.md'
        - 'Testing Requirements': 'sdp/testing-plan.md'
        - 'DevSecOps Requirements': 'sdp/devsecops.md'
        - 'Software Requirements': 'sdp/software-requirements.md'
        - 'Branch, Merge, Release Guidance': 'sdp/branch-merge-release.md'
        - 'General Python Coding Guidelines': 'sdp/coding-guidelines.md'
      - 'Documentation':
        - requirements/documentation/index.md
      - 'Product':
        - requirements/product/index.md
        - 'Classification Policy': 'requirements/product/classification.md'
        - 'Open-sourcing Guidelines': 'requirements/product/open-source.md'
        - 'Product Naming Guidelines': 'requirements/product/naming.md'
  - 'Calendar': 
    - 'Increment 3 (11 OCT 23 - 30 JAN 24)': 'calendar/inc3.md'
    - 'Increment 4 (31 JAN 24 - 23 APR 24)': 'calendar/inc4.md'
    - 'Increment 5 (24 APR 24 - 15 JUL 24)': 'calendar/inc5.md'
  - 'Teams':
    - 'ARiA': 'teams/aria.md'
    - 'IBM': 'teams/ibm.md'
    - 'Kitware': 'teams/kitware.md'
    - 'MIT-LL': 'teams/mitll.md'
    - 'MORSE': 'teams/morse.md'
    - 'Team MetroStar': 'teams/msqs.md'
    - 'PM Team': 'teams/pm.md'
    - 'System Team': 'teams/systems.md'
    - 'TwoSix': 'teams/twosix.md'
  - 'Presentations': # use to host all of our demo videos and presentations. need to figure out how to do this.
    - presentations/index.md
  - 'Program Board': https://app.mural.co/t/ecis6578/m/ecis6578/1697134244478/58b5177575b43e6f5caf6feb82d840410a6ceff5?sender=u4d7fc200d51cbdba67ba7346

