# See https://www.mkdocs.org/user-guide/configuration/ for documentation!

site_name: [TEMPLATE TITLE] # edit this line!
site_url: https://jatic.pages.jatic.net/[project_path] # edit this line! 
repo_url: https://gitlab.jatic.net/jatic/[project_path] # edit this line!

# everything below can be left alone
site_dir: ../public
docs_dir: ../docs
theme: readthedocs
plugins:
    - search
    - awesome-pages
nav:
    - Home: README.md
    - ...
