site_name: [TEMPLATE TITLE]
site_url: https://jatic.pages.jatic.net/[project_path]
repo_url: https://gitlab.jatic.net/jatic/[project_path]
# example site_url: https://jatic.pages.jatic.net/jatic/docs/org-process
# example repo_url: https://gitlab.jatic.net/jatic/docs/org-process
site_dir: ../public
docs_dir: ../docs
#theme: readthedocs
theme: material
plugins:
    - search
    - awesome-pages
nav:
    - Home: README.md
    - ...
